"""User regular_budget at 150, and non-nullable

Revision ID: 071a6546fc40
Revises: 9c35d26d3f60
Create Date: 2024-08-09 13:21:59.533213

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "071a6546fc40"
down_revision = "9c35d26d3f60"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "regular_budget",
            existing_type=sa.FLOAT(),
            nullable=False,
            server_default=sa.text("150.00"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "regular_budget",
            existing_type=sa.FLOAT(),
            nullable=True,
            server_default=sa.text("0.00"),
        )

    # ### end Alembic commands ###
