"""Add new column prompts

Revision ID: 5887daab01dd
Revises: c3fd095f18a2
Create Date: 2024-07-23 15:02:39.689556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5887daab01dd'
down_revision = 'c3fd095f18a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompts', postgresql.JSONB(astext_type=sa.Text()), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_response', schema=None) as batch_op:
        batch_op.drop_column('prompts')

    # ### end Alembic commands ###
