"""Add OpenAIUsage table

Revision ID: 897ea17c354c
Revises: 9084d1fe30f7
Create Date: 2024-07-24 17:52:30.293422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "897ea17c354c"
down_revision = "9084d1fe30f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "openai_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prompt_response_id", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["prompt_response_id"],
            ["prompt_response.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("openai_usage")
    # ### end Alembic commands ###
