"""Remove column called messages

Revision ID: 9084d1fe30f7
Revises: 4ffd784181ce
Create Date: 2024-07-23 16:31:28.151787

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9084d1fe30f7"
down_revision = "4ffd784181ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prompt_response", schema=None) as batch_op:
        batch_op.drop_column("messages")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prompt_response", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("messages", sa.TEXT(), autoincrement=False, nullable=False)
        )

    # ### end Alembic commands ###
