"""Add team id to the prompt response

Revision ID: 953019ca42a6
Revises: 98fd3bdd909f
Create Date: 2024-08-12 16:30:23.048480

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = "953019ca42a6"
down_revision = "98fd3bdd909f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prompt_response", schema=None) as batch_op:
        batch_op.add_column(sa.Column("team_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "teams", ["team_id"], ["id"])

    # ### end Alembic commands ###
    # Get the connection
    conn = op.get_bind()

    # Define the tables
    teams_table = table("teams", column("id", sa.Integer))
    prompt_response_table = table(
        "prompt_response", column("id", sa.Integer), column("team_id", sa.Integer)
    )

    # Get the ID of the first team
    team_id = conn.execute(sa.select(teams_table.c.id).limit(1)).scalar()

    # Update all prompt responses to belong to the first team
    conn.execute(prompt_response_table.update().values(team_id=team_id))

    # Make the team_id column non-nullable
    with op.batch_alter_table("prompt_response", schema=None) as batch_op:
        batch_op.alter_column("team_id", existing_type=sa.Integer(), nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prompt_response", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("team_id")

    # ### end Alembic commands ###
