"""Create prompt_response table

Revision ID: 98ec2b047e77
Revises:
Create Date: 2024-07-12 16:11:28.481550

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "98ec2b047e77"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_response",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prompt", sa.String(), nullable=False),
        sa.Column("response", sa.String(), nullable=False),
        sa.Column("response_time", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prompt_response")
    # ### end Alembic commands ###
