"""Remove column prompt

Revision ID: ee18938c5ff9
Revises: 5887daab01dd
Create Date: 2024-07-23 16:02:33.651523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee18938c5ff9'
down_revision = '5887daab01dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_response', schema=None) as batch_op:
        batch_op.drop_column('prompt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
